### ISSUE TITLE
HttpTransfer setRequestSSOCookie() policy

### ISSUE THREAD

**Issue by at88mph** [opencadc/core#16]
The current version of HttpTransfer.setRequestSSOCookie() [705] assumes that whomever submits a cookie to add to a request will be on the same host (domain) as the service call's domain.  This is not the case with more and more portable clients.

Case:
1. User A logs in to www.mysite.com and gets a cookie back as the authentication was successful.
2. The VOSpace Client on www.mysite.com tries to obtain authenticated data from www.canfar.net on the User A's behalf, but the cookie is not set on the Request because the cookie's domain is www.mysite.com rather than www.canfar.net.

This could signal the need for a more Global SSO system, or maybe a change in how cookies are accepted by the service.  This is, more or less, what OAuth would handle.

Short term, could we patch this method to just add all of the cookies that the current Subject has in hand?

**Comment by pdowler** [comment]
The current behaviour is conservative but it would not be approp to re-use cookies when calling other domains. Since the current code is probably wrong in it's handling of sub-domains we should keep this issue open until we have a situation where that needs to be fixed.

**Comment by pdowler** [comment]
This is now obsolete since we implemented multiple domain scope inside a signed cookie.
